name: Go Format Check

on:
  push:
    branches:
      - '**'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check formatting
        run: |
          output=$(gofmt -l .)
          if [ -n "$output" ]; then
            echo "The following files are not formatted correctly:"
            echo "$output"
            exit 1
          fi
          echo "All Go files are correctly formatted."